version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "project-maintainer"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates for ESLint and related packages
      # ESLint 9.x has breaking changes that require significant config updates
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/parser"
        update-types: ["version-update:semver-major"]
      # Ignore TypeScript major updates for now due to compatibility issues
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "project-maintainer"
    commit-message:
      prefix: "ci"
      include: "scope"