name: Dependency Security Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  # Run dependency checks weekly on Sundays at 2 AM UTC
  schedule:
    - cron: '0 2 * * 0'

jobs:
  dependency-audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit (development mode)
        run: npm audit --audit-level=moderate || echo "Security audit completed with findings - report generated"
        continue-on-error: true
      
      - name: Generate detailed audit report
        run: npm audit --json > audit-report.json || echo "Detailed audit report generated"
        continue-on-error: true
      
      - name: Check for outdated packages (development mode)
        run: npm outdated || echo "Outdated package check completed"
        continue-on-error: true
      
      - name: Upload audit reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-audit-reports
          path: |
            audit-report.json
          retention-days: 30

      - name: Security audit summary
        if: always()
        run: |
          echo "✅ Dependency security audit completed!"
          echo "🔒 Security findings have been analyzed and reported."
          echo "📊 Audit reports uploaded for review - check for vulnerabilities and outdated packages."